//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpmc
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Маршрут.
    /// </summary>
    // *** Start programmer edit section *** (DSERout CustomAttributes)

    // *** End programmer edit section *** (DSERout CustomAttributes)
    [AutoAltered()]
    [Caption("Маршрут")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Code as \'Code\'",
            "Name as \'Name\'",
            "ProcessTime as \'Process time\'",
            "Tool as \'Tool\'",
            "Tool.Name as \'Name\'",
            "UnitMetr as \'Unit metr\'",
            "UnitMetr.Name as \'Name\'",
            "Material as \'Material\'",
            "Material.Name as \'Name\'",
            "Operation as \'Operation\'",
            "Operation.Name as \'Name\'"}, Hidden=new string[] {
            "Tool.Name",
            "UnitMetr.Name",
            "Material.Name",
            "Operation.Name"})]
    [MasterViewDefineAttribute("AuditView", "Tool", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("AuditView", "UnitMetr", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("AuditView", "Material", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("AuditView", "Operation", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("DSERoutE", new string[] {
            "ProcessTime as \'Время обработки\'",
            "UnitMetr as \'Ед. измерения\'",
            "UnitMetr.ShortName",
            "Tool as \'Инструмент\'",
            "Tool.Name",
            "Material as \'Материал\'",
            "Material.Name",
            "Operation as \'Операция\'",
            "Operation.Name",
            "OrderMachine",
            "NameMachine",
            "CodeMachine"}, Hidden=new string[] {
            "UnitMetr.ShortName",
            "Tool.Name",
            "Material.Name",
            "Operation.Name"})]
    [MasterViewDefineAttribute("DSERoutE", "UnitMetr", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ShortName")]
    [MasterViewDefineAttribute("DSERoutE", "Tool", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("DSERoutE", "Material", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("DSERoutE", "Operation", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class DSERout : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private int fCode;
        
        private string fName;
        
        private int fOrderMachine;
        
        private string fNameMachine;
        
        private int fCodeMachine;
        
        private double fProcessTime;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private Cpmc.Tool fTool;
        
        private Cpmc.UnitMetr fUnitMetr;
        
        private Cpmc.Material fMaterial;
        
        private Cpmc.Operation fOperation;
        
        private Cpmc.DSE fDSE;
        
        // *** Start programmer edit section *** (DSERout CustomMembers)

        // *** End programmer edit section *** (DSERout CustomMembers)

        
        /// <summary>
        /// Code.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.Code CustomAttributes)

        // *** End programmer edit section *** (DSERout.Code CustomAttributes)
        public virtual int Code
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.Code Get start)

                // *** End programmer edit section *** (DSERout.Code Get start)
                int result = this.fCode;
                // *** Start programmer edit section *** (DSERout.Code Get end)

                // *** End programmer edit section *** (DSERout.Code Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.Code Set start)

                // *** End programmer edit section *** (DSERout.Code Set start)
                this.fCode = value;
                // *** Start programmer edit section *** (DSERout.Code Set end)

                // *** End programmer edit section *** (DSERout.Code Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.Name CustomAttributes)

        // *** End programmer edit section *** (DSERout.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.Name Get start)

                // *** End programmer edit section *** (DSERout.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (DSERout.Name Get end)

                // *** End programmer edit section *** (DSERout.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.Name Set start)

                // *** End programmer edit section *** (DSERout.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (DSERout.Name Set end)

                // *** End programmer edit section *** (DSERout.Name Set end)
            }
        }
        
        /// <summary>
        /// OrderMachine.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.OrderMachine CustomAttributes)

        // *** End programmer edit section *** (DSERout.OrderMachine CustomAttributes)
        public virtual int OrderMachine
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.OrderMachine Get start)

                // *** End programmer edit section *** (DSERout.OrderMachine Get start)
                int result = this.fOrderMachine;
                // *** Start programmer edit section *** (DSERout.OrderMachine Get end)

                // *** End programmer edit section *** (DSERout.OrderMachine Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.OrderMachine Set start)

                // *** End programmer edit section *** (DSERout.OrderMachine Set start)
                this.fOrderMachine = value;
                // *** Start programmer edit section *** (DSERout.OrderMachine Set end)

                // *** End programmer edit section *** (DSERout.OrderMachine Set end)
            }
        }
        
        /// <summary>
        /// NameMachine.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.NameMachine CustomAttributes)

        // *** End programmer edit section *** (DSERout.NameMachine CustomAttributes)
        [StrLen(255)]
        public virtual string NameMachine
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.NameMachine Get start)

                // *** End programmer edit section *** (DSERout.NameMachine Get start)
                string result = this.fNameMachine;
                // *** Start programmer edit section *** (DSERout.NameMachine Get end)

                // *** End programmer edit section *** (DSERout.NameMachine Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.NameMachine Set start)

                // *** End programmer edit section *** (DSERout.NameMachine Set start)
                this.fNameMachine = value;
                // *** Start programmer edit section *** (DSERout.NameMachine Set end)

                // *** End programmer edit section *** (DSERout.NameMachine Set end)
            }
        }
        
        /// <summary>
        /// CodeMachine.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.CodeMachine CustomAttributes)

        // *** End programmer edit section *** (DSERout.CodeMachine CustomAttributes)
        public virtual int CodeMachine
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.CodeMachine Get start)

                // *** End programmer edit section *** (DSERout.CodeMachine Get start)
                int result = this.fCodeMachine;
                // *** Start programmer edit section *** (DSERout.CodeMachine Get end)

                // *** End programmer edit section *** (DSERout.CodeMachine Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.CodeMachine Set start)

                // *** End programmer edit section *** (DSERout.CodeMachine Set start)
                this.fCodeMachine = value;
                // *** Start programmer edit section *** (DSERout.CodeMachine Set end)

                // *** End programmer edit section *** (DSERout.CodeMachine Set end)
            }
        }
        
        /// <summary>
        /// ProcessTime.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.ProcessTime CustomAttributes)

        // *** End programmer edit section *** (DSERout.ProcessTime CustomAttributes)
        public virtual double ProcessTime
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.ProcessTime Get start)

                // *** End programmer edit section *** (DSERout.ProcessTime Get start)
                double result = this.fProcessTime;
                // *** Start programmer edit section *** (DSERout.ProcessTime Get end)

                // *** End programmer edit section *** (DSERout.ProcessTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.ProcessTime Set start)

                // *** End programmer edit section *** (DSERout.ProcessTime Set start)
                this.fProcessTime = value;
                // *** Start programmer edit section *** (DSERout.ProcessTime Set end)

                // *** End programmer edit section *** (DSERout.ProcessTime Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.CreateTime CustomAttributes)

        // *** End programmer edit section *** (DSERout.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.CreateTime Get start)

                // *** End programmer edit section *** (DSERout.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (DSERout.CreateTime Get end)

                // *** End programmer edit section *** (DSERout.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.CreateTime Set start)

                // *** End programmer edit section *** (DSERout.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (DSERout.CreateTime Set end)

                // *** End programmer edit section *** (DSERout.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.Creator CustomAttributes)

        // *** End programmer edit section *** (DSERout.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.Creator Get start)

                // *** End programmer edit section *** (DSERout.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (DSERout.Creator Get end)

                // *** End programmer edit section *** (DSERout.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.Creator Set start)

                // *** End programmer edit section *** (DSERout.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (DSERout.Creator Set end)

                // *** End programmer edit section *** (DSERout.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.EditTime CustomAttributes)

        // *** End programmer edit section *** (DSERout.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.EditTime Get start)

                // *** End programmer edit section *** (DSERout.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (DSERout.EditTime Get end)

                // *** End programmer edit section *** (DSERout.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.EditTime Set start)

                // *** End programmer edit section *** (DSERout.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (DSERout.EditTime Set end)

                // *** End programmer edit section *** (DSERout.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.Editor CustomAttributes)

        // *** End programmer edit section *** (DSERout.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.Editor Get start)

                // *** End programmer edit section *** (DSERout.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (DSERout.Editor Get end)

                // *** End programmer edit section *** (DSERout.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.Editor Set start)

                // *** End programmer edit section *** (DSERout.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (DSERout.Editor Set end)

                // *** End programmer edit section *** (DSERout.Editor Set end)
            }
        }
        
        /// <summary>
        /// Маршрут.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.Tool CustomAttributes)

        // *** End programmer edit section *** (DSERout.Tool CustomAttributes)
        [PropertyStorage(new string[] {
                "Tool"})]
        //[NotNull()]
        public virtual Cpmc.Tool Tool
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.Tool Get start)

                // *** End programmer edit section *** (DSERout.Tool Get start)
                Cpmc.Tool result = this.fTool;
                // *** Start programmer edit section *** (DSERout.Tool Get end)

                // *** End programmer edit section *** (DSERout.Tool Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.Tool Set start)

                // *** End programmer edit section *** (DSERout.Tool Set start)
                this.fTool = value;
                // *** Start programmer edit section *** (DSERout.Tool Set end)

                // *** End programmer edit section *** (DSERout.Tool Set end)
            }
        }
        
        /// <summary>
        /// Маршрут.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.UnitMetr CustomAttributes)

        // *** End programmer edit section *** (DSERout.UnitMetr CustomAttributes)
        [PropertyStorage(new string[] {
                "UnitMetr"})]
        //[NotNull()]
        public virtual Cpmc.UnitMetr UnitMetr
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.UnitMetr Get start)

                // *** End programmer edit section *** (DSERout.UnitMetr Get start)
                Cpmc.UnitMetr result = this.fUnitMetr;
                // *** Start programmer edit section *** (DSERout.UnitMetr Get end)

                // *** End programmer edit section *** (DSERout.UnitMetr Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.UnitMetr Set start)

                // *** End programmer edit section *** (DSERout.UnitMetr Set start)
                this.fUnitMetr = value;
                // *** Start programmer edit section *** (DSERout.UnitMetr Set end)

                // *** End programmer edit section *** (DSERout.UnitMetr Set end)
            }
        }
        
        /// <summary>
        /// Маршрут.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.Material CustomAttributes)

        // *** End programmer edit section *** (DSERout.Material CustomAttributes)
        [PropertyStorage(new string[] {
                "Material"})]
        //[NotNull()]
        public virtual Cpmc.Material Material
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.Material Get start)

                // *** End programmer edit section *** (DSERout.Material Get start)
                Cpmc.Material result = this.fMaterial;
                // *** Start programmer edit section *** (DSERout.Material Get end)

                // *** End programmer edit section *** (DSERout.Material Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.Material Set start)

                // *** End programmer edit section *** (DSERout.Material Set start)
                this.fMaterial = value;
                // *** Start programmer edit section *** (DSERout.Material Set end)

                // *** End programmer edit section *** (DSERout.Material Set end)
            }
        }
        
        /// <summary>
        /// Маршрут.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.Operation CustomAttributes)

        // *** End programmer edit section *** (DSERout.Operation CustomAttributes)
        [PropertyStorage(new string[] {
                "Operation"})]
        //[NotNull()]
        public virtual Cpmc.Operation Operation
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.Operation Get start)

                // *** End programmer edit section *** (DSERout.Operation Get start)
                Cpmc.Operation result = this.fOperation;
                // *** Start programmer edit section *** (DSERout.Operation Get end)

                // *** End programmer edit section *** (DSERout.Operation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.Operation Set start)

                // *** End programmer edit section *** (DSERout.Operation Set start)
                this.fOperation = value;
                // *** Start programmer edit section *** (DSERout.Operation Set end)

                // *** End programmer edit section *** (DSERout.Operation Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку Cpmc.DSE.
        /// </summary>
        // *** Start programmer edit section *** (DSERout.DSE CustomAttributes)

        // *** End programmer edit section *** (DSERout.DSE CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "DSE"})]
        public virtual Cpmc.DSE DSE
        {
            get
            {
                // *** Start programmer edit section *** (DSERout.DSE Get start)

                // *** End programmer edit section *** (DSERout.DSE Get start)
                Cpmc.DSE result = this.fDSE;
                // *** Start programmer edit section *** (DSERout.DSE Get end)

                // *** End programmer edit section *** (DSERout.DSE Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DSERout.DSE Set start)

                // *** End programmer edit section *** (DSERout.DSE Set start)
                this.fDSE = value;
                // *** Start programmer edit section *** (DSERout.DSE Set end)

                // *** End programmer edit section *** (DSERout.DSE Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Cpmc.DSERout));
                }
            }
            
            /// <summary>
            /// "DSERoutE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DSERoutE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DSERoutE", typeof(Cpmc.DSERout));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of DSERout.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDSERout CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfDSERout CustomAttributes)
    public class DetailArrayOfDSERout : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (Cpmc.DetailArrayOfDSERout members)

        // *** End programmer edit section *** (Cpmc.DetailArrayOfDSERout members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type DSERout by index.
        /// </summary>
        /// <summary>
        /// Adds object with type DSERout.
        /// </summary>
        public DetailArrayOfDSERout(Cpmc.DSE fDSE) : 
                base(typeof(DSERout), ((ICSSoft.STORMNET.DataObject)(fDSE)))
        {
        }
        
        public Cpmc.DSERout this[int index]
        {
            get
            {
                return ((Cpmc.DSERout)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(Cpmc.DSERout dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
