//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpmc
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (Machine CustomAttributes)

    // *** End programmer edit section *** (Machine CustomAttributes)
    [AutoAltered()]
    [Caption("Оборудование")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Code as \'Code\'",
            "Name as \'Name\'",
            "Description as \'Description\'",
            "CreateTime as \'Create time\'",
            "Creator as \'Creator\'",
            "EditTime as \'Edit time\'",
            "Editor as \'Editor\'"})]
    [View("MachineE", new string[] {
            "Code as \'Код\'",
            "Name as \'Наименование\'",
            "Description as \'Описание\'"})]
    [View("MachineL", new string[] {
            "Code as \'Код\'",
            "Name as \'Наименование\'",
            "CreateTime as \'Дата создания\'",
            "Creator as \'Создатель\'",
            "EditTime as \'Дата редактирования\'",
            "Editor as \'Редактор\'"})]
    public class Machine : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private int fCode;
        
        private string fName;
        
        private string fDescription;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (Machine CustomMembers)

        // *** End programmer edit section *** (Machine CustomMembers)

        
        /// <summary>
        /// Code.
        /// </summary>
        // *** Start programmer edit section *** (Machine.Code CustomAttributes)

        // *** End programmer edit section *** (Machine.Code CustomAttributes)
        public virtual int Code
        {
            get
            {
                // *** Start programmer edit section *** (Machine.Code Get start)

                // *** End programmer edit section *** (Machine.Code Get start)
                int result = this.fCode;
                // *** Start programmer edit section *** (Machine.Code Get end)

                // *** End programmer edit section *** (Machine.Code Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Machine.Code Set start)

                // *** End programmer edit section *** (Machine.Code Set start)
                this.fCode = value;
                // *** Start programmer edit section *** (Machine.Code Set end)

                // *** End programmer edit section *** (Machine.Code Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Machine.Name CustomAttributes)

        // *** End programmer edit section *** (Machine.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Machine.Name Get start)

                // *** End programmer edit section *** (Machine.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Machine.Name Get end)

                // *** End programmer edit section *** (Machine.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Machine.Name Set start)

                // *** End programmer edit section *** (Machine.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Machine.Name Set end)

                // *** End programmer edit section *** (Machine.Name Set end)
            }
        }
        
        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Machine.Description CustomAttributes)

        // *** End programmer edit section *** (Machine.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Machine.Description Get start)

                // *** End programmer edit section *** (Machine.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Machine.Description Get end)

                // *** End programmer edit section *** (Machine.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Machine.Description Set start)

                // *** End programmer edit section *** (Machine.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Machine.Description Set end)

                // *** End programmer edit section *** (Machine.Description Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Machine.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Machine.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Machine.CreateTime Get start)

                // *** End programmer edit section *** (Machine.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Machine.CreateTime Get end)

                // *** End programmer edit section *** (Machine.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Machine.CreateTime Set start)

                // *** End programmer edit section *** (Machine.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Machine.CreateTime Set end)

                // *** End programmer edit section *** (Machine.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Machine.Creator CustomAttributes)

        // *** End programmer edit section *** (Machine.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Machine.Creator Get start)

                // *** End programmer edit section *** (Machine.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Machine.Creator Get end)

                // *** End programmer edit section *** (Machine.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Machine.Creator Set start)

                // *** End programmer edit section *** (Machine.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Machine.Creator Set end)

                // *** End programmer edit section *** (Machine.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Machine.EditTime CustomAttributes)

        // *** End programmer edit section *** (Machine.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Machine.EditTime Get start)

                // *** End programmer edit section *** (Machine.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Machine.EditTime Get end)

                // *** End programmer edit section *** (Machine.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Machine.EditTime Set start)

                // *** End programmer edit section *** (Machine.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Machine.EditTime Set end)

                // *** End programmer edit section *** (Machine.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Machine.Editor CustomAttributes)

        // *** End programmer edit section *** (Machine.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Machine.Editor Get start)

                // *** End programmer edit section *** (Machine.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Machine.Editor Get end)

                // *** End programmer edit section *** (Machine.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Machine.Editor Set start)

                // *** End programmer edit section *** (Machine.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Machine.Editor Set end)

                // *** End programmer edit section *** (Machine.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Cpmc.Machine));
                }
            }
            
            /// <summary>
            /// "MachineE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MachineE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MachineE", typeof(Cpmc.Machine));
                }
            }
            
            /// <summary>
            /// "MachineL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MachineL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MachineL", typeof(Cpmc.Machine));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
