//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpmc
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Материал.
    /// </summary>
    // *** Start programmer edit section *** (Material CustomAttributes)

    // *** End programmer edit section *** (Material CustomAttributes)
    [AutoAltered()]
    [Caption("Материал")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Name as \'Name\'",
            "Code as \'Code\'",
            "CreateTime as \'Create time\'",
            "Creator as \'Creator\'",
            "EditTime as \'Edit time\'",
            "Editor as \'Editor\'",
            "UnitMetr as \'Unit metr\'",
            "UnitMetr.Name as \'Name\'"})]
    [View("MaterialE", new string[] {
            "Code as \'Код\'",
            "Name as \'Наименование\'",
            "UnitMetr as \'Ед. измерения\'",
            "UnitMetr.ShortName"}, Hidden=new string[] {
            "UnitMetr.ShortName"})]
    [MasterViewDefineAttribute("MaterialE", "UnitMetr", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ShortName")]
    [View("MaterialL", new string[] {
            "Code as \'Крд\'",
            "Name as \'Наименование\'",
            "UnitMetr.ShortName as \'Ед. измерения\'"})]
    public class Material : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fName;
        
        private int fCode;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private Cpmc.UnitMetr fUnitMetr;
        
        // *** Start programmer edit section *** (Material CustomMembers)

        // *** End programmer edit section *** (Material CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Material.Name CustomAttributes)

        // *** End programmer edit section *** (Material.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Material.Name Get start)

                // *** End programmer edit section *** (Material.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Material.Name Get end)

                // *** End programmer edit section *** (Material.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Material.Name Set start)

                // *** End programmer edit section *** (Material.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Material.Name Set end)

                // *** End programmer edit section *** (Material.Name Set end)
            }
        }
        
        /// <summary>
        /// Code.
        /// </summary>
        // *** Start programmer edit section *** (Material.Code CustomAttributes)

        // *** End programmer edit section *** (Material.Code CustomAttributes)
        public virtual int Code
        {
            get
            {
                // *** Start programmer edit section *** (Material.Code Get start)

                // *** End programmer edit section *** (Material.Code Get start)
                int result = this.fCode;
                // *** Start programmer edit section *** (Material.Code Get end)

                // *** End programmer edit section *** (Material.Code Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Material.Code Set start)

                // *** End programmer edit section *** (Material.Code Set start)
                this.fCode = value;
                // *** Start programmer edit section *** (Material.Code Set end)

                // *** End programmer edit section *** (Material.Code Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Material.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Material.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Material.CreateTime Get start)

                // *** End programmer edit section *** (Material.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Material.CreateTime Get end)

                // *** End programmer edit section *** (Material.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Material.CreateTime Set start)

                // *** End programmer edit section *** (Material.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Material.CreateTime Set end)

                // *** End programmer edit section *** (Material.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Material.Creator CustomAttributes)

        // *** End programmer edit section *** (Material.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Material.Creator Get start)

                // *** End programmer edit section *** (Material.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Material.Creator Get end)

                // *** End programmer edit section *** (Material.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Material.Creator Set start)

                // *** End programmer edit section *** (Material.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Material.Creator Set end)

                // *** End programmer edit section *** (Material.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Material.EditTime CustomAttributes)

        // *** End programmer edit section *** (Material.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Material.EditTime Get start)

                // *** End programmer edit section *** (Material.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Material.EditTime Get end)

                // *** End programmer edit section *** (Material.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Material.EditTime Set start)

                // *** End programmer edit section *** (Material.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Material.EditTime Set end)

                // *** End programmer edit section *** (Material.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Material.Editor CustomAttributes)

        // *** End programmer edit section *** (Material.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Material.Editor Get start)

                // *** End programmer edit section *** (Material.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Material.Editor Get end)

                // *** End programmer edit section *** (Material.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Material.Editor Set start)

                // *** End programmer edit section *** (Material.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Material.Editor Set end)

                // *** End programmer edit section *** (Material.Editor Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (Material.UnitMetr CustomAttributes)

        // *** End programmer edit section *** (Material.UnitMetr CustomAttributes)
        [PropertyStorage(new string[] {
                "UnitMetr"})]
        public virtual Cpmc.UnitMetr UnitMetr
        {
            get
            {
                // *** Start programmer edit section *** (Material.UnitMetr Get start)

                // *** End programmer edit section *** (Material.UnitMetr Get start)
                Cpmc.UnitMetr result = this.fUnitMetr;
                // *** Start programmer edit section *** (Material.UnitMetr Get end)

                // *** End programmer edit section *** (Material.UnitMetr Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Material.UnitMetr Set start)

                // *** End programmer edit section *** (Material.UnitMetr Set start)
                this.fUnitMetr = value;
                // *** Start programmer edit section *** (Material.UnitMetr Set end)

                // *** End programmer edit section *** (Material.UnitMetr Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Cpmc.Material));
                }
            }
            
            /// <summary>
            /// "MaterialE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MaterialE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MaterialE", typeof(Cpmc.Material));
                }
            }
            
            /// <summary>
            /// "MaterialL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MaterialL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MaterialL", typeof(Cpmc.Material));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
