//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpmc
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Plan item.
    /// </summary>
    // *** Start programmer edit section *** (PlanItem CustomAttributes)

    // *** End programmer edit section *** (PlanItem CustomAttributes)
    [AutoAltered()]
    [Caption("Строка плана")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "DSE as \'DSE\'",
            "DSE.Name as \'Name\'"}, Hidden=new string[] {
            "DSE.Name"})]
    [MasterViewDefineAttribute("AuditView", "DSE", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("PlanItemE", new string[] {
            "DSE as \'Код\'",
            "DSE.Code",
            "DSE.Name as \'Наименование\'",
            "DSE.ProcessOrder.Name as \'Порядок обработки\'"}, Hidden=new string[] {
            "DSE.Code"})]
    [MasterViewDefineAttribute("PlanItemE", "DSE", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Code")]
    public class PlanItem : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private Cpmc.DSE fDSE;
        
        private Cpmc.Plan fPlan;
        
        // *** Start programmer edit section *** (PlanItem CustomMembers)

        // *** End programmer edit section *** (PlanItem CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (PlanItem.CreateTime CustomAttributes)

        // *** End programmer edit section *** (PlanItem.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (PlanItem.CreateTime Get start)

                // *** End programmer edit section *** (PlanItem.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (PlanItem.CreateTime Get end)

                // *** End programmer edit section *** (PlanItem.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PlanItem.CreateTime Set start)

                // *** End programmer edit section *** (PlanItem.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (PlanItem.CreateTime Set end)

                // *** End programmer edit section *** (PlanItem.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (PlanItem.Creator CustomAttributes)

        // *** End programmer edit section *** (PlanItem.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (PlanItem.Creator Get start)

                // *** End programmer edit section *** (PlanItem.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (PlanItem.Creator Get end)

                // *** End programmer edit section *** (PlanItem.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PlanItem.Creator Set start)

                // *** End programmer edit section *** (PlanItem.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (PlanItem.Creator Set end)

                // *** End programmer edit section *** (PlanItem.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (PlanItem.EditTime CustomAttributes)

        // *** End programmer edit section *** (PlanItem.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (PlanItem.EditTime Get start)

                // *** End programmer edit section *** (PlanItem.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (PlanItem.EditTime Get end)

                // *** End programmer edit section *** (PlanItem.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PlanItem.EditTime Set start)

                // *** End programmer edit section *** (PlanItem.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (PlanItem.EditTime Set end)

                // *** End programmer edit section *** (PlanItem.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (PlanItem.Editor CustomAttributes)

        // *** End programmer edit section *** (PlanItem.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (PlanItem.Editor Get start)

                // *** End programmer edit section *** (PlanItem.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (PlanItem.Editor Get end)

                // *** End programmer edit section *** (PlanItem.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PlanItem.Editor Set start)

                // *** End programmer edit section *** (PlanItem.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (PlanItem.Editor Set end)

                // *** End programmer edit section *** (PlanItem.Editor Set end)
            }
        }
        
        /// <summary>
        /// Plan item.
        /// </summary>
        // *** Start programmer edit section *** (PlanItem.DSE CustomAttributes)

        // *** End programmer edit section *** (PlanItem.DSE CustomAttributes)
        [PropertyStorage(new string[] {
                "DSE"})]
        [NotNull()]
        public virtual Cpmc.DSE DSE
        {
            get
            {
                // *** Start programmer edit section *** (PlanItem.DSE Get start)

                // *** End programmer edit section *** (PlanItem.DSE Get start)
                Cpmc.DSE result = this.fDSE;
                // *** Start programmer edit section *** (PlanItem.DSE Get end)

                // *** End programmer edit section *** (PlanItem.DSE Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PlanItem.DSE Set start)

                // *** End programmer edit section *** (PlanItem.DSE Set start)
                this.fDSE = value;
                // *** Start programmer edit section *** (PlanItem.DSE Set end)

                // *** End programmer edit section *** (PlanItem.DSE Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку Cpmc.Plan.
        /// </summary>
        // *** Start programmer edit section *** (PlanItem.Plan CustomAttributes)

        // *** End programmer edit section *** (PlanItem.Plan CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Plan"})]
        public virtual Cpmc.Plan Plan
        {
            get
            {
                // *** Start programmer edit section *** (PlanItem.Plan Get start)

                // *** End programmer edit section *** (PlanItem.Plan Get start)
                Cpmc.Plan result = this.fPlan;
                // *** Start programmer edit section *** (PlanItem.Plan Get end)

                // *** End programmer edit section *** (PlanItem.Plan Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PlanItem.Plan Set start)

                // *** End programmer edit section *** (PlanItem.Plan Set start)
                this.fPlan = value;
                // *** Start programmer edit section *** (PlanItem.Plan Set end)

                // *** End programmer edit section *** (PlanItem.Plan Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Cpmc.PlanItem));
                }
            }
            
            /// <summary>
            /// "PlanItemE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PlanItemE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PlanItemE", typeof(Cpmc.PlanItem));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of PlanItem.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfPlanItem CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfPlanItem CustomAttributes)
    public class DetailArrayOfPlanItem : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (Cpmc.DetailArrayOfPlanItem members)

        // *** End programmer edit section *** (Cpmc.DetailArrayOfPlanItem members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type PlanItem by index.
        /// </summary>
        /// <summary>
        /// Adds object with type PlanItem.
        /// </summary>
        public DetailArrayOfPlanItem(Cpmc.Plan fPlan) : 
                base(typeof(PlanItem), ((ICSSoft.STORMNET.DataObject)(fPlan)))
        {
        }
        
        public Cpmc.PlanItem this[int index]
        {
            get
            {
                return ((Cpmc.PlanItem)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(Cpmc.PlanItem dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
