//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpmc
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Порядок обработки.
    /// </summary>
    // *** Start programmer edit section *** (ProcessOrder CustomAttributes)

    // *** End programmer edit section *** (ProcessOrder CustomAttributes)
    [AutoAltered()]
    [Caption("Порядок обработки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("AuditView", "ProcessOrderItem", "AuditView", true, "", "Process order item", true, new string[] {
            ""})]
    [View("ProcessOrderE", new string[] {
            "Name as \'Наименование\'"})]
    [AssociatedDetailViewAttribute("ProcessOrderE", "ProcessOrderItem", "ProcessOrderItemE", true, "", "Оборудование", true, new string[] {
            ""})]
    [View("ProcessOrderL", new string[] {
            "Name as \'Наименование\'"})]
    public class ProcessOrder : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fName;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private Cpmc.DetailArrayOfProcessOrderItem fProcessOrderItem;
        
        // *** Start programmer edit section *** (ProcessOrder CustomMembers)

        // *** End programmer edit section *** (ProcessOrder CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ProcessOrder.Name CustomAttributes)

        // *** End programmer edit section *** (ProcessOrder.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ProcessOrder.Name Get start)

                // *** End programmer edit section *** (ProcessOrder.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ProcessOrder.Name Get end)

                // *** End programmer edit section *** (ProcessOrder.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProcessOrder.Name Set start)

                // *** End programmer edit section *** (ProcessOrder.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ProcessOrder.Name Set end)

                // *** End programmer edit section *** (ProcessOrder.Name Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (ProcessOrder.CreateTime CustomAttributes)

        // *** End programmer edit section *** (ProcessOrder.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (ProcessOrder.CreateTime Get start)

                // *** End programmer edit section *** (ProcessOrder.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (ProcessOrder.CreateTime Get end)

                // *** End programmer edit section *** (ProcessOrder.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProcessOrder.CreateTime Set start)

                // *** End programmer edit section *** (ProcessOrder.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (ProcessOrder.CreateTime Set end)

                // *** End programmer edit section *** (ProcessOrder.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (ProcessOrder.Creator CustomAttributes)

        // *** End programmer edit section *** (ProcessOrder.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (ProcessOrder.Creator Get start)

                // *** End programmer edit section *** (ProcessOrder.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (ProcessOrder.Creator Get end)

                // *** End programmer edit section *** (ProcessOrder.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProcessOrder.Creator Set start)

                // *** End programmer edit section *** (ProcessOrder.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (ProcessOrder.Creator Set end)

                // *** End programmer edit section *** (ProcessOrder.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (ProcessOrder.EditTime CustomAttributes)

        // *** End programmer edit section *** (ProcessOrder.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (ProcessOrder.EditTime Get start)

                // *** End programmer edit section *** (ProcessOrder.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (ProcessOrder.EditTime Get end)

                // *** End programmer edit section *** (ProcessOrder.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProcessOrder.EditTime Set start)

                // *** End programmer edit section *** (ProcessOrder.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (ProcessOrder.EditTime Set end)

                // *** End programmer edit section *** (ProcessOrder.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (ProcessOrder.Editor CustomAttributes)

        // *** End programmer edit section *** (ProcessOrder.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (ProcessOrder.Editor Get start)

                // *** End programmer edit section *** (ProcessOrder.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (ProcessOrder.Editor Get end)

                // *** End programmer edit section *** (ProcessOrder.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProcessOrder.Editor Set start)

                // *** End programmer edit section *** (ProcessOrder.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (ProcessOrder.Editor Set end)

                // *** End programmer edit section *** (ProcessOrder.Editor Set end)
            }
        }
        
        /// <summary>
        /// Порядок обработки.
        /// </summary>
        // *** Start programmer edit section *** (ProcessOrder.ProcessOrderItem CustomAttributes)

        // *** End programmer edit section *** (ProcessOrder.ProcessOrderItem CustomAttributes)
        public virtual Cpmc.DetailArrayOfProcessOrderItem ProcessOrderItem
        {
            get
            {
                // *** Start programmer edit section *** (ProcessOrder.ProcessOrderItem Get start)

                // *** End programmer edit section *** (ProcessOrder.ProcessOrderItem Get start)
                if ((this.fProcessOrderItem == null))
                {
                    this.fProcessOrderItem = new Cpmc.DetailArrayOfProcessOrderItem(this);
                }
                Cpmc.DetailArrayOfProcessOrderItem result = this.fProcessOrderItem;
                // *** Start programmer edit section *** (ProcessOrder.ProcessOrderItem Get end)

                // *** End programmer edit section *** (ProcessOrder.ProcessOrderItem Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProcessOrder.ProcessOrderItem Set start)

                // *** End programmer edit section *** (ProcessOrder.ProcessOrderItem Set start)
                this.fProcessOrderItem = value;
                // *** Start programmer edit section *** (ProcessOrder.ProcessOrderItem Set end)

                // *** End programmer edit section *** (ProcessOrder.ProcessOrderItem Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Cpmc.ProcessOrder));
                }
            }
            
            /// <summary>
            /// "ProcessOrderE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProcessOrderE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProcessOrderE", typeof(Cpmc.ProcessOrder));
                }
            }
            
            /// <summary>
            /// "ProcessOrderL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProcessOrderL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProcessOrderL", typeof(Cpmc.ProcessOrder));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
