//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpmc
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// tPlanAlgorithm.
    /// </summary>
    // *** Start programmer edit section *** (tPlanAlgorithm CustomAttributes)

    // *** End programmer edit section *** (tPlanAlgorithm CustomAttributes)
    public enum tPlanAlgorithm
    {
        All,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.Jonson CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.Jonson CustomAttributes)
        Jonson,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.Front CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.Front CustomAttributes)
        Front,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.NEH CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.NEH CustomAttributes)
        NEH,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.Lex CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.Lex CustomAttributes)
        Lex,
    }
}
