//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpmc
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// tPlanAlgorithm.
    /// </summary>
    // *** Start programmer edit section *** (tPlanAlgorithm CustomAttributes)

    // *** End programmer edit section *** (tPlanAlgorithm CustomAttributes)
    public enum tPlanAlgorithm
    {
        Jonson,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.Genetic CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.Genetic CustomAttributes)
        Genetic,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.MinLabor CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.MinLabor CustomAttributes)
        MinLabor,
		
		/// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.MaxLabor CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.MaxLabor CustomAttributes)
        MaxLabor,
		
		/// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.Random CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.Random CustomAttributes)
        Random,
		
		/// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanAlgorithm.OperationNumber CustomAttributes)

        // *** End programmer edit section *** (tPlanAlgorithm.OperationNumber CustomAttributes)
        OperationNumber,
    }
}
