//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpmc
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T status.
    /// </summary>
    // *** Start programmer edit section *** (tPlanState CustomAttributes)

    // *** End programmer edit section *** (tPlanState CustomAttributes)
    public enum tPlanState
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanState.New CustomAttributes)

        // *** End programmer edit section *** (tPlanState.New CustomAttributes)
        New,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanState.Suspended CustomAttributes)

        // *** End programmer edit section *** (tPlanState.Suspended CustomAttributes)
        Suspended,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanState.Approved CustomAttributes)

        // *** End programmer edit section *** (tPlanState.Approved CustomAttributes)
        Approved,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanState.NotApproved CustomAttributes)

        // *** End programmer edit section *** (tPlanState.NotApproved CustomAttributes)
        NotApproved,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanState.Archive CustomAttributes)

        // *** End programmer edit section *** (tPlanState.Archive CustomAttributes)
        Archive,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tPlanState.Done CustomAttributes)

        // *** End programmer edit section *** (tPlanState.Done CustomAttributes)
        Done,
    }
}
